### ISSUE TITLE
Website Issues

### ISSUE THREAD

**Issue by pshutt4** [pshutt4/CMPS480Summer2021#28]
We found 3 issues with our website in our team's meeting, 

1. Empty space on the Checkout page.

2. Fonts were not matching with other pages. 

3. Pay button for the cart was showing as pay $NAN

**Comment by Eali83** [comment]
To solve this issue, I opened the main.js file and scroll down to the function of calculating total amount before doing the payment. On line 187 you just need to remove { $${cartTotal} with a single quotation marks and the problem has been solved.

**Comment by pshutt4** [comment]
Added a coupon image to the Checkout page to remove some of the empty space.

**Comment by AhmedAlbugami** [comment]
We also have changed the font styling on all pages to match one another.

**Comment by kmanning1** [comment]
We removed the homepage link in the check out page as well

**Comment by hsdrame** [comment]
we harmonized the font style, in order to have a lot more enthusiasm.
